### ISSUE TITLE
Terrain collision and spawn

### ISSUE THREAD

**Issue by Yesat** [Wuschelbueb/Battleship#8]
Now we have island we need to avoid ghost ships.

**Comment by Yesat** [comment]
The system as it's being done currently has two elements.

1. map preview, without any collider
2. terrain chunk that generate only when the game starts.

So we need to check the collisions with the chunks described in [TerrainChunks.cs](https://github.com/Wuschelbueb/Battleship/blob/master/Assets/Scripts/TerrainChunk.cs) and called with [TerrainGenerator.cs](https://github.com/Wuschelbueb/Battleship/blob/master/Assets/Scripts/TerrainChunk.cs)

**Comment by MrPascalCase** [comment]
take a look at the ship.addtriggers()
maybe not the best code (wrote that really early), but gets a similar job done. 
then you can differenciate the collision detection at ship.oncolliderenter()
dont forget to add tags to islands (mapchunk.tag = "island";)

**Comment by Yesat** [comment]
Or another way could be to simply check when the ship collide with "Untagged". tag works on game objects and I can't seem to find how it could work.
